repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .idea/*
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
      - id: go-mod-tidy-repo
      - id: go-test-repo-mod
      - id: go-vet-repo-mod
      - id: go-revive-repo-mod
      - id: go-sec-mod
      - id: go-staticcheck-mod
      - id: golangci-lint-repo-mod
        args: ["--fix"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
