version: 3

tasks:
  watch:
    cmds:
      - task: build
    desc: "Watch files"
    silent: false
    watch: true
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
  build:
    desc: Builds the Go application
    watch: false
    sources:
      - '**/*.go'
    cmds:
      - go build # ...
