services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
      VAULT_API_ADDR: "https://0.0.0.0:8201"
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"false", "tls_cert_file":"/data/localhost.crt", "tls_key_file":"/data/localhost.key"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: 'root-token'
      VAULT_TOKEN: 'root-token'
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id="root-token"
    volumes:
      - ./certs:/data
